Second set of changes to transition from single-account to multi-account design
* Add logic to use Secrets stored in SecretsManager for Passwords, in addition to existing explitly specified Passwords
* Add logic to use SecretsManager
* Remove Standard from config file names
* Improve logic to detect incorrect EncryptionKeys when adding Users as seed data

diff --git a/OpenVPNAS/configure-openvpnas b/OpenVPNAS/configure-openvpnas
--- a/OpenVPNAS/configure-openvpnas
+++ b/OpenVPNAS/configure-openvpnas
@@ -14,9 +14,13 @@
 bindir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 confdir=${bindir%/*}/conf
 
-standardgroupsdatfile=$confdir/standard-groups.dat
+zone=$(curl -s -m 60 http://169.254.169.254/latest/meta-data/placement/availability-zone)
+region=${zone:: -1}
+zonecode=${zone: -1}
+
+groupsdatfile=$confdir/groups.dat
 customgroupsdatfile=$confdir/custom-groups.dat
-standardusersdatfile=$confdir/standard-users.dat
+usersdatfile=$confdir/users.dat
 customusersdatfile=$confdir/custom-users.dat
 
 logfile=/var/log/$(basename $0).log
@@ -30,10 +34,12 @@ host=$(hostname -s)
 domain=$(hostname -d)
 openvpn_user=openvpn
 unset openvpn_password
+unset openvpn_password_secret
 ldap_server1=$(sed -n -e 's/^nameserver //p' /etc/resolv.conf | sed -n -e '1p')
 ldap_server2=$(sed -n -e 's/^nameserver //p' /etc/resolv.conf | sed -n -e '2p')
 ldap_bind_cn="OpenVPN Server"
 unset ldap_bind_password
+unset ldap_bind_password_secret
 
 ldap_debug_level=10 # Normally 0
 ldap_trace_level=10 # Normally 0
@@ -44,9 +50,9 @@ ldap_trace_level=10 # Normally 0
 usage() {
     echo "Usage: ${BASH_SOURCE##*/} [-n] [-v] [-l] [-a type]"
     echo "                  [-h host] [-d domain]"
-    echo "                  [-u user] [-p password]"
+    echo "                  [-u user] [-p password] [-s secret]"
     echo "                  [-1 server] [-2 server]"
-    echo "                  [-B cn] [-P password]"
+    echo "                  [-B cn] [-P password] [-S secret]"
     echo "  -n              non-interactive"
     echo "  -v              verbose"
     echo "  -l              lock OpenVPN Administrator User"
@@ -54,11 +60,13 @@ usage() {
     echo "  -h host         Host (default: $host)"
     echo "  -d domain       Domain (default: $domain)"
     echo "  -u user         OpenVPN Administrator User (default: $openvpn_user)"
-    echo "  -p password     OpenVPN Administrator Password (default: $openvpn_password)"
+    echo "  -p password     OpenVPN Administrator Password"
+    echo "  -s secret-id    OpenVPN Administrator Password SecretId"
     echo "  -1 server       Primary LDAP Server (default: $ldap_server1)"
     echo "  -2 server       Backup LDAP Server (default: $ldap_server2)"
     echo "  -B cn           LDAP Bind CN (default: $ldap_bind_cn)"
-    echo "  -P password     LDAP Bind Password (default: $ldap_bind_password)"
+    echo "  -P password     LDAP Bind Password"
+    echo "  -S seret-id     LDAP Bind Password SecretId"
 }
 
 console() {
@@ -110,7 +118,7 @@ if [ $(ip2decimal $ldap_server1) -gt $(ip2decimal $ldap_server2) ]; then
     ldap_server2=$t
 fi
 
-while getopts nvla:h:d:u:p:1:2:B:P:? arg; do
+while getopts nvla:h:d:u:p:s:1:2:B:P:S:? arg; do
     case $arg in
     n)  interactive=0;;
     v)  ((verbose++));;
@@ -120,10 +128,12 @@ while getopts nvla:h:d:u:p:1:2:B:P:? arg; do
     d)  domain="$OPTARG";;
     u)  openvpn_user="$OPTARG";;
     p)  openvpn_password="$OPTARG";;
+    s)  openvpn_password_secret="$OPTARG";;
     1)  ldap_server1="$OPTARG";;
     2)  ldap_server2="$OPTARG";;
     B)  ldap_bind_cn="$OPTARG";;
     P)  ldap_bind_password="$OPTARG";;
+    S)  ldap_bind_password_secret="$OPTARG";;
     ?)  usage
         exit 1;;
     esac
@@ -176,9 +186,9 @@ else
     esac
 fi
 
-if [ -z $openvpn_password ]; then
-    console ERROR "-p password missing!"
-    console ERROR "Could not automatically determine OpenVPN password, and it was not specified as a parameter"
+if [ -z $openvpn_password ] && [ -z $openvpn_password_secret ]; then
+    console ERROR "-p secret or -s secret missing!"
+    console ERROR "OpenVPN Password must be specified explicitly or as a SecretId when stored in SecretsManager, neither were specified as a parameter"
     exit 16
 fi
 
@@ -201,22 +211,22 @@ if [ $auth = ldap ]; then
         exit 24
     fi
 
-    if [ -z $ldap_bind_password ]; then
-        console ERROR "-P password missing!"
-        console ERROR "Could not automatically determine LDAP bind password, and it was not specified as a parameter"
+    if [ -z $ldap_bind_password ] && [ -z $ldap_bind_password_secret ]; then
+        console ERROR "-P password or -S secret missing!"
+        console ERROR "LDAP bind password must be specified explicitly or as a SecretId when stored in SecretsManager, neither were specified as a parameter"
         exit 26
     fi
 fi
 
-if [ ! -r $standardgroupsdatfile ]; then
-    console ERROR "Could not find Standard Groups Data File: $standardgroupsdatfile"
+if [ ! -r $groupsdatfile ]; then
+    console ERROR "Could not find Groups Data File: $groupsdatfile"
     exit 30
 fi
 if [ ! -r $customgroupsdatfile ]; then
     console WARN "Could not find Custom Groups Data File: $customgroupsdatfile"
 fi
-if [ ! -r $standardusersdatfile ]; then
-    console ERROR "Could not find Standard Users Data File: $standardusersdatfile"
+if [ ! -r $usersdatfile ]; then
+    console ERROR "Could not find Users Data File: $usersdatfile"
     exit 34
 fi
 if [ ! -r $customusersdatfile ]; then
@@ -225,6 +235,23 @@ fi
 
 
 #  5. Main
+
+if [ ! -z $openvpn_password_secret ]; then
+  console "Obtaining '$openvpn_password_secret' secret from SecretsManager..."
+
+  openvpn_password=$(aws secretsmanager get-secret-value --secret-id $openvpn_password_secret \
+                                                         --query 'SecretString' \
+                                                         --region $region --output text)
+  RC=$?
+
+  if [ $RC = 0 ]; then
+    console "Obtained '$openvpn_password_secret' secret successfully"
+  else
+    console "Could not obtain '$openvpn_password_secret' secret! Error: $RC"
+    exit 99
+  fi
+fi
+
 
 console "Setting '$openvpn_user' user password"
 echo "$openvpn_user:$openvpn_password" | chpasswd
@@ -283,7 +310,7 @@ console "Configuring OpenVPNAS Client Settings"
 # Currently none
 
 
-console "Configuring OpenVPNAS Standard Groups"
+console "Configuring OpenVPNAS Groups"
 
 while IFS=: read -r group superuser; do
     [ ${group:0:1} = \# ] && continue
@@ -293,7 +320,7 @@ while IFS=: read -r group superuser; do
     if [ $superuser = true ]; then
         /usr/local/openvpn_as/scripts/sacli --user "$group" --key "prop_superuser" --value "true" UserPropPut
     fi
-done < $standardgroupsdatfile
+done < $groupsdatfile
 
 if [ -r $customgroupsdatfile ]; then
     console "Configuring OpenVPNAS Custom Groups"
@@ -309,13 +336,13 @@ if [ -r $customgroupsdatfile ]; then
     done < $customgroupsdatfile
 fi
 
-console "Configuring OpenVPNAS Standard Users"
+console "Configuring OpenVPNAS Users"
 while IFS=: read -r user group pam_hash openvpn_hash; do
     [ ${user:0:1} = \# ] && continue
     console "- $user ($group)"
     /usr/local/openvpn_as/scripts/sacli --user "$user" --key "type" --value "user_connect" UserPropPut
     /usr/local/openvpn_as/scripts/sacli --user "$user" --key "conn_group" --value "$group" UserPropPut
-done < $standardusersdatfile
+done < $usersdatfile
 
 if [ -r $customusersdatfile ]; then
     console "Configuring OpenVPNAS Custom Users"
@@ -333,12 +360,12 @@ case $auth in
     console "Configuring OpenVPNAS Local Authentication Settings"
     /usr/local/openvpn_as/scripts/sacli --key "auth.module.type" --value "local" ConfigPut
 
-    console "Configuring OpenVPNAS Local Authentication Passwords for Standard Users"
+    console "Configuring OpenVPNAS Local Authentication Passwords for Users"
     while IFS=: read -r user group pam_hash openvpn_hash; do
         [ ${user:0:1} = \# ] && continue
         console "- $user"
         /usr/local/openvpn_as/scripts/sacli --user "$user" --key "pvt_password_digest" --value "$openvpn_hash" UserPropPut
-    done < $standardusersdatfile
+    done < $usersdatfile
 
     if [ -r $customusersdatfile ]; then
         console "Configuring OpenVPNAS Local Authentication Passwords for Custom Users"
@@ -356,14 +383,14 @@ case $auth in
     console "Configuring OpenVPNAS PAM Authentication Settings"
     /usr/local/openvpn_as/scripts/sacli --key "auth.module.type" --value "pam" ConfigPut
 
-    console "Configuring OpenVPNAS PAM Authentication Users and Passwords for Standard Users"
+    console "Configuring OpenVPNAS PAM Authentication Users and Passwords for Users"
     while IFS=: read -r user group pam_hash openvpn_hash; do
         [ ${user:0:1} = \# ] && continue
         id -u $user &> /dev/null && continue
         console "- $user"
         useradd -s /sbin/nologin $user
         echo "$user:$pam_hash" | chpasswd -e
-    done < $standardusersdatfile
+    done < $usersdatfile
 
     if [ -r $customusersdatfile ]; then
         console "Configuring OpenVPNAS PAM Authentication Users and Passwords for Custom Users"
